name: Version Update

on:
  push:
    branches:
      - master

jobs:
  sanitize_config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Sanitize sensitive config values
        run: python scripts/sanitize-config.py

  update_version:
    runs-on: ubuntu-latest
    needs: sanitize_config

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run version update script
        run: python scripts/version-update.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
